language:
	- cpp
compiler:
	- gcc
	- clang
before_install:
	- sudo apt-get update -qq
	- sudo apt-get install -qq -y cmake libboost-all-dev
env:
	- BUILD_TYPE="Debug"
	- BUILD_TYPE="Release"
script:
	- mkdir _build
	- cd _build
	- cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" ..
	- cmake --build .
	- cmake --build . --target install
